# Generated by Django 4.1.1 on 2022-10-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='guitar',
        ),
    ]
