# Generated by Django 4.1.1 on 2022-10-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_accessory_guitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='user',
        ),
        migrations.AddField(
            model_name='guitar',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
